/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caixaeletronicoui;

import javax.swing.JOptionPane;

/**
 *
 * @author noturno
 */
public class InterfaceCaixa extends javax.swing.JFrame {
    
    private Conta objConta = null;
    
    

    /**
     * Creates new form InterfaceCaixa
     */
    public InterfaceCaixa() {
        initComponents();
        this.objConta = new Conta();
        txtSaida.enable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtSaida = new javax.swing.JTextPane();
        saldoBtn = new javax.swing.JButton();
        depositoBtn = new javax.swing.JButton();
        saqueBtn = new javax.swing.JButton();
        sairBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(0, 0, 0));

        txtSaida.setBorder(null);
        txtSaida.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        txtSaida.setForeground(new java.awt.Color(0, 255, 157));
        jScrollPane1.setViewportView(txtSaida);

        saldoBtn.setBackground(new java.awt.Color(156, 156, 156));
        saldoBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        saldoBtn.setText("SALDO");
        saldoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldoBtnActionPerformed(evt);
            }
        });

        depositoBtn.setBackground(new java.awt.Color(156, 156, 156));
        depositoBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        depositoBtn.setText("DEPÓSITO");
        depositoBtn.setToolTipText("");
        depositoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositoBtnActionPerformed(evt);
            }
        });

        saqueBtn.setBackground(new java.awt.Color(156, 156, 156));
        saqueBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        saqueBtn.setText("SAQUE");
        saqueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saqueBtnActionPerformed(evt);
            }
        });

        sairBtn.setBackground(new java.awt.Color(156, 156, 156));
        sairBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sairBtn.setText("SAIR");
        sairBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(saldoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(depositoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(saqueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sairBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saldoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(depositoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(saqueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(sairBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saldoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldoBtnActionPerformed
        //System.out.println("SALDO: " + this.objConta.verificarSaldo());
        txtSaida.setText("SALDO: " + this.objConta.verificarSaldo());
    }//GEN-LAST:event_saldoBtnActionPerformed

    private void depositoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositoBtnActionPerformed
        
         float valorDeposito = Float.parseFloat(JOptionPane.showInputDialog("INFORME UM VALOR DE DEPÓSITO"));
        
         if(valorDeposito > 0){
             
             objConta.realizarDeposito(valorDeposito);
             txtSaida.setText("SALDO: " + this.objConta.verificarSaldo());
             
         }else{
             JOptionPane.showMessageDialog(null,"!DIGITE UM VALOR VÁLIDO!", " )= VALOR INVÁLIDO =(", 
                     JOptionPane.ERROR_MESSAGE);
         }
    }//GEN-LAST:event_depositoBtnActionPerformed

    private void saqueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saqueBtnActionPerformed
         float valorSaque = Float.parseFloat(JOptionPane.showInputDialog("INFORME UM VALOR DE SAQUE"));
         
         if(valorSaque <= this.objConta.saldo){
             
             objConta.realizarSaque(valorSaque);
             txtSaida.setText("SALDO: " + this.objConta.verificarSaldo());
             
         }else{
             JOptionPane.showMessageDialog(null, "SEU SALDO É DE R$" + this.objConta.saldo + "\nPOR FAVOR \n" +
                     "DIGITE UM VALOR VÁLIDO", " )= VALOR INVÁLIDO =(", JOptionPane.ERROR_MESSAGE);
         }
         
    }//GEN-LAST:event_saqueBtnActionPerformed

    private void sairBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairBtnActionPerformed
        JOptionPane.showConfirmDialog(null,"DESEJA SAIR?", "SAIR", JOptionPane.YES_NO_OPTION); 
        System.exit(0);
    }//GEN-LAST:event_sairBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceCaixa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton depositoBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton sairBtn;
    private javax.swing.JButton saldoBtn;
    private javax.swing.JButton saqueBtn;
    private javax.swing.JTextPane txtSaida;
    // End of variables declaration//GEN-END:variables
}
